name = "brrrn-hub"
main = "src/worker.js"
compatibility_date = "2026-07-01"

[[kv_namespaces]]
binding = "BRRRN_KV"
id = "f38a6ca8579d4d4f8e0d33bf192db806"

[[durable_objects.bindings]]
name = "COORDINATOR"
class_name = "Coordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Coordinator"]
